[package]
name = "apod-nasa-scraper-rs"
version = "0.1.0"
authors = ["Max Gonzih <gonzih@gmail.com>"]
edition = "2018"

[dependencies]
regex = "1"
tokio = { version = "1", features = ["full"] }
clap = "3.0.0-beta.2"
crabler = "0.1.16"
# crabler ={ path = "/home/gnzh/mydev/crabler", features = ["debug"] }
