[package]
name = "apod-nasa-scraper-rs"
version = "0.1.0"
authors = ["Max Gonzih <gonzih@gmail.com>"]
edition = "2018"

[dependencies]
regex = "1"
crabquery = "0.1.1"
reqwest = { version = "0.10", features = [] }
tokio = { version = "0.2", features = ["full"] }
clap = { git = "https://github.com/clap-rs/clap" }
futures = "0.3.4"
