[package]
name = "apod-nasa-scraper-rs"
version = "0.1.0"
authors = ["Max Gonzih <gonzih@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1"
scraper = "0.11.0"
reqwest = { version = "0.10", features = [] }
tokio = { version = "0.2", features = ["full"] }
clap = { git = "https://github.com/clap-rs/clap" }
